2025-03-05 19:12:58,030 INFO    MainThread:10852 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7.dev1
2025-03-05 19:12:58,030 INFO    MainThread:10852 [wandb_setup.py:_flush():67] Configure stats pid to 10852
2025-03-05 19:12:58,030 INFO    MainThread:10852 [wandb_setup.py:_flush():67] Loading settings from /home/akshay/.config/wandb/settings
2025-03-05 19:12:58,030 INFO    MainThread:10852 [wandb_setup.py:_flush():67] Loading settings from /home/akshay/Desktop/DL/assignment-01/wandb/settings
2025-03-05 19:12:58,030 INFO    MainThread:10852 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 19:12:58,030 INFO    MainThread:10852 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/akshay/Desktop/DL/assignment-01/wandb/run-20250305_191258-yo0ok00x/logs/debug.log
2025-03-05 19:12:58,030 INFO    MainThread:10852 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/akshay/Desktop/DL/assignment-01/wandb/run-20250305_191258-yo0ok00x/logs/debug-internal.log
2025-03-05 19:12:58,030 INFO    MainThread:10852 [wandb_init.py:init():761] calling init triggers
2025-03-05 19:12:58,030 INFO    MainThread:10852 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10, '_wandb': {}}
2025-03-05 19:12:58,030 INFO    MainThread:10852 [wandb_init.py:init():784] starting backend
2025-03-05 19:12:58,030 INFO    MainThread:10852 [wandb_init.py:init():788] sending inform_init request
2025-03-05 19:12:58,033 INFO    MainThread:10852 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-05 19:12:58,033 INFO    MainThread:10852 [wandb_init.py:init():803] backend started and connected
2025-03-05 19:12:58,034 INFO    MainThread:10852 [wandb_init.py:init():896] updated telemetry
2025-03-05 19:12:58,035 INFO    MainThread:10852 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-05 19:12:58,443 ERROR   MainThread:10852 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/akshay/anaconda3/envs/ML_gpu/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/home/akshay/anaconda3/envs/ML_gpu/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity my-awesome-team-name not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-03-05 19:12:58,444 WARNING MsgRouterThr:10852 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/akshay/anaconda3/envs/ML_gpu/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/akshay/anaconda3/envs/ML_gpu/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/akshay/anaconda3/envs/ML_gpu/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/akshay/anaconda3/envs/ML_gpu/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/akshay/anaconda3/envs/ML_gpu/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-05 19:12:58,444 INFO    MsgRouterThr:10852 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
